import type { NextConfig } from "next";

/**
 * /movies and /movies-like slugs used to be hand-picked (e.g. "amelie"). They're now generated by
 * the same filmId() function the private films table uses, so a public catalog entry and a real
 * logged film share one id whenever title+year match — which is what lets a movie page eventually
 * show real aggregate data about itself. That changed the slug for every film that already had a
 * live public URL, so old links need a permanent redirect rather than quietly 404ing.
 */
const RENAMED_MOVIE_SLUGS: Array<[oldSlug: string, newSlug: string]> = [
  ["chungking-express", "chungking-express-1994"],
  ["in-the-mood-for-love", "in-the-mood-for-love-2000"],
  ["paris-texas", "paris-texas-1984"],
  ["aftersun", "aftersun-2022"],
  ["perfect-days", "perfect-days-2023"],
  ["portrait-of-a-lady-on-fire", "portrait-of-a-lady-on-fire-2019"],
  ["columbus", "columbus-2017"],
  ["drive-my-car", "drive-my-car-2021"],
  ["past-lives", "past-lives-2023"],
  ["blue-valentine", "blue-valentine-2010"],
  ["eternal-sunshine", "eternal-sunshine-of-the-spotless-mind-2004"],
  ["before-sunset", "before-sunset-2004"],
  ["amelie", "amelie-2001"],
  ["ratatouille", "ratatouille-2007"],
  ["lost-in-translation", "lost-in-translation-2003"],
  ["worst-person-in-the-world", "the-worst-person-in-the-world-2021"],
  ["moonlight", "moonlight-2016"],
  ["her", "her-2013"],
  ["burning", "burning-2018"],
  ["shoplifters", "shoplifters-2018"],
];

// Only 17 of the 20 films above have a /movies-like page (Columbus, Her, and Burning don't clear
// the minimum-related-films bar) — redirecting the other three would send visitors to a 404.
const NO_MOVIES_LIKE_PAGE = new Set(["columbus", "her", "burning"]);

const nextConfig: NextConfig = {
  turbopack: {
    root: __dirname,
  },
  experimental: {
    // Server Actions cap request bodies at 1MB by default, which a Letterboxd diary export with
    // reviews can exceed. Raised deliberately, and only to 2MB — the import action enforces the
    // same ceiling itself so an oversized file gets a real message instead of a framework error.
    serverActions: {
      bodySizeLimit: "2mb",
    },
  },
  async redirects() {
    return RENAMED_MOVIE_SLUGS.flatMap(([oldSlug, newSlug]) => {
      const routes = [{ source: `/movies/${oldSlug}`, destination: `/movies/${newSlug}`, permanent: true }];
      if (!NO_MOVIES_LIKE_PAGE.has(oldSlug)) {
        routes.push({ source: `/movies-like/${oldSlug}`, destination: `/movies-like/${newSlug}`, permanent: true });
      }
      return routes;
    });
  },
};

export default nextConfig;
